#!/usr/bin/env node
/**
 * Build Script: PWA Pipeline
 * 1. Flatten inverters-catalog.json → assets/inverter-db.js (ESM)
 * 2. Generate icons from SVG via sharp
 * 3. Write precache manifest into sw.js
 * 4. Update PROJECT_MAP.md
 */

import fs from 'fs';
import path from 'path';

const CATALOG_PATH = 'inverters-catalog.json';
const INVERTER_DB_PATH = 'assets/inverter-db.js';
const SW_PATH = 'sw.js';
const PROJECT_MAP_PATH = 'PROJECT_MAP.md';
const ICON_SVG = 'icons/icon.svg';

// --- Utility: pretty JSON value ---
function pv(val) {
  if (typeof val === 'string') return `'${val.replace(/'/g, "\\'")}'`;
  if (Array.isArray(val) || (typeof val === 'object' && val !== null)) return JSON.stringify(val);
  return String(val);
}

// --- 1. Load & Flatten Catalog ---
const catalog = JSON.parse(fs.readFileSync(CATALOG_PATH, 'utf-8'));

function flattenCatalog(catalog) {
  const db = [];
  for (const mfr of catalog.manufacturers) {
    for (const series of mfr.series) {
      const base = {
        brand: mfr.name,
        series: series.name,
        type: series.type,
        phase: series.phase,
        batteryV: { min: series.batteryVoltageRange[0], max: series.batteryVoltageRange[1] },
        batteryType: series.batteryType,
        mpptRange: { min: series.mpptVoltageRange[0], max: series.mpptVoltageRange[1] },
        mpptCount: series.mpptCount,
        maxInputCurrentPerMPPT: series.maxInputCurrentPerMppt,
        maxIscPerMPPT: series.maxIscPerMppt,
        maxAcPassthroughCurrent: series.maxAcPassthroughCurrent,
        maxEff: series.maxEfficiency,
        euEff: series.euEfficiency,
        batChargeEffPv: series.batChargeEffPv,
        batChargeEffAc: series.batChargeEffAc,
        batDischargeEff: series.batDischargeEff,
        surgePowerMultiplier: series.surgePowerMultiplier,
        surgeTimeSec: series.surgeTimeSec,
        switchTimeMs: series.switchTimeMs,
        ip: series.ipRating,
        cooling: series.cooling,
        topology: series.topology,
        dims: series.dimensions,
        weight: series.weight,
        tempRange: series.tempRange,
        altitude: series.altitude,
        comm: series.commInterfaces,
        display: series.display,
        wifiOpt: series.wifiOptional,
        lanOpt: series.lanOptional,
        gprsOpt: series.gprsOptional,
        certs: series.certifications,
        parallel: series.parallelMax,
        vendorExtras: series.vendorExtras || {}
      };

      for (const model of series.models) {
        db.push({
          ...base,
          ...model,
          id: model.sku,
          maxPVPower: model.maxPvPowerW,
          maxInputCurrentPerMPPT: model.maxInputCurrentPerMppt || base.maxInputCurrentPerMPPT,
          maxIscPerMPPT: model.maxIscPerMppt || base.maxIscPerMPPT,
          maxChargeCurrentA: model.maxChargeCurrentA,
          maxDischargeCurrentA: model.maxDischargeCurrentA,
          maxChargePowerW: model.maxChargePowerW,
          maxStringsPerMppt: model.maxStringsPerMppt,
          maxStrings: model.maxStringsTotal || 2
        });
      }
    }
  }
  return db;
}

const INVERTER_DB = flattenCatalog(catalog);
console.log(`  Catalog: ${INVERTER_DB.length} models from ${catalog.manufacturers.length} manufacturers`);

// --- 2. Generate inverter-db.js (ESM) ---
function generateInverterDBCode(db) {
  const lines = [
    '// =====================================================================',
    '// MODULE: Inverter Database (ES Module)',
    '// Auto-generated by build.mjs from inverters-catalog.json',
    '// =====================================================================',
    '',
    'export var PANEL_SPECS={',
    ...Object.entries({
      300:{Vmp:32.5,Voc:39.2,Imp:9.23,Isc:9.78},
      350:{Vmp:34.2,Voc:41.1,Imp:10.24,Isc:10.85},
      450:{Vmp:41.5,Voc:49.8,Imp:10.84,Isc:11.49},
      550:{Vmp:42.8,Voc:51.3,Imp:12.85,Isc:13.62},
      570:{Vmp:43.2,Voc:51.8,Imp:13.19,Isc:13.97},
      600:{Vmp:43.8,Voc:52.5,Imp:13.70,Isc:14.50},
      650:{Vmp:44.5,Voc:53.4,Imp:14.61,Isc:15.45},
      670:{Vmp:44.8,Voc:53.7,Imp:14.96,Isc:15.82},
      700:{Vmp:45.2,Voc:54.2,Imp:15.49,Isc:16.35},
      720:{Vmp:45.5,Voc:54.5,Imp:15.82,Isc:16.69},
      750:{Vmp:45.8,Voc:54.9,Imp:16.38,Isc:17.26},
      780:{Vmp:46.1,Voc:55.3,Imp:16.92,Isc:17.83}
    }).map(([k,v], i, arr) => `  ${k}:${JSON.stringify(v)}${i < arr.length - 1 ? ',' : ''}`),
    '};',
    '',
    'export var INVERTER_DB = ['
  ];

  for (const inv of db) {
    lines.push('  {');
    const fields = [
      'id', 'brand', 'series', 'model', 'ratedW', 'type', 'phase',
      'batteryV', 'batteryType', 'maxPVPower', 'mpptRange', 'mpptCount',
      'maxInputCurrentPerMPPT', 'maxIscPerMPPT', 'maxStringsPerMPPT',
      'maxStrings', 'maxChargeCurrentA', 'maxDischargeCurrentA', 'maxChargePowerW',
      'ratedGridV', 'ratedGridFreq', 'ratedOutputA', 'maxOutputA',
      'maxAcPassthroughA', 'maxEff', 'euEff', 'batChargeEffPv', 'batChargeEffAc',
      'batDischargeEff', 'surgePower', 'surgeTimeSec', 'switchTimeMs',
      'ip', 'cooling', 'topology', 'dims', 'weight', 'tempRange', 'altitude',
      'comm', 'display', 'wifiOpt', 'lanOpt', 'gprsOpt', 'certs', 'parallel',
      'vendorExtras'
    ];
    for (const f of fields) {
      if (inv[f] !== undefined) {
        const key = f === 'maxChargeCurrentA' ? 'maxChargeCurrent'
                  : f === 'maxDischargeCurrentA' ? 'maxDischargeCurrent'
                  : f === 'maxChargePowerW' ? 'maxChargePower'
                  : f === 'maxStringsPerMPPT' ? 'maxStringsPerMPPT'
                  : f;
        lines.push(`    ${key}: ${pv(inv[f])},`);
      }
    }
    lines.push('  },');
  }
  lines.push('];');
  lines.push('');
  lines.push('export function getInverterById(id) {');
  lines.push('  for (var i = 0; i < INVERTER_DB.length; i++) {');
  lines.push('    if (INVERTER_DB[i].id === id) return INVERTER_DB[i];');
  lines.push('  }');
  lines.push('  return null;');
  lines.push('}');
  return lines.join('\n');
}

const INVERTER_DB_CODE = generateInverterDBCode(INVERTER_DB);
fs.writeFileSync(INVERTER_DB_PATH, INVERTER_DB_CODE, 'utf-8');
console.log(`  Written: ${INVERTER_DB_PATH} (${(INVERTER_DB_CODE.length / 1024).toFixed(1)} KB)`);

// --- 3. Generate icons from SVG (if sharp available) ---
async function generateIcons() {
  try {
    const sharp = (await import('sharp')).default;
    const svgBuffer = fs.readFileSync(ICON_SVG);
    const sizes = [
      { name: 'icon-72.png', size: 72 },
      { name: 'icon-96.png', size: 96 },
      { name: 'icon-128.png', size: 128 },
      { name: 'icon-144.png', size: 144 },
      { name: 'icon-152.png', size: 152 },
      { name: 'icon-192.png', size: 192 },
      { name: 'icon-384.png', size: 384 },
      { name: 'icon-512.png', size: 512 },
      { name: 'maskable-192.png', size: 192, maskable: true },
      { name: 'maskable-512.png', size: 512, maskable: true },
      { name: 'apple-touch-icon.png', size: 180 },
      { name: 'favicon.ico', size: 32 }
    ];
    for (const s of sizes) {
      let img = sharp(svgBuffer).resize(s.size, s.size);
      const outPath = path.join('icons', s.name);
      if (s.name.endsWith('.ico')) {
        await img.png().toFile(outPath);
      } else {
        await img.png().toFile(outPath);
      }
      console.log(`  Icon: ${s.name} (${s.size}×${s.size})`);
    }
    console.log('  Icons generated');
  } catch (e) {
    console.log('  Icons: skipped (sharp not available, run: npm install sharp --save-dev)');
  }
}

await generateIcons();

// --- 4. Generate precache list for sw.js ---
function generateSW(db) {
  const precacheUrls = [
    './', './index.html', './manifest.json',
    './assets/styles.css', './assets/app.js', './assets/inverter-db.js',
    './icons/icon.svg',
    './icons/icon-72.png', './icons/icon-96.png', './icons/icon-128.png',
    './icons/icon-144.png', './icons/icon-152.png', './icons/icon-192.png',
    './icons/icon-384.png', './icons/icon-512.png',
    './icons/maskable-192.png', './icons/maskable-512.png',
    './icons/apple-touch-icon.png', './icons/favicon.ico'
  ];

  const swCode = `// Service Worker - Solar Calculator PWA
// Auto-generated by build.mjs - DO NOT EDIT manually
// Generated: ${new Date().toISOString()}

var CACHE_NAME = 'solar-calc-v${Date.now()}';
var PRECACHE_URLS = ${JSON.stringify(precacheUrls, null, 2)};

var DATA_URLS = [
  './inverters-catalog.json',
  './cost-assumptions.json',
  './load-profile.json'
];

self.addEventListener('install', function(event) {
  event.waitUntil(
    caches.open(CACHE_NAME).then(function(cache) {
      return cache.addAll(PRECACHE_URLS);
    }).then(function() {
      return self.skipWaiting();
    })
  );
});

self.addEventListener('activate', function(event) {
  event.waitUntil(
    caches.keys().then(function(cacheNames) {
      return Promise.all(
        cacheNames.filter(function(name) {
          return name !== CACHE_NAME;
        }).map(function(name) {
          return caches.delete(name);
        })
      );
    }).then(function() {
      return self.clients.claim();
    })
  );
});

self.addEventListener('fetch', function(event) {
  var url = new URL(event.request.url);
  var path = url.pathname.replace(/^.*\\/\\/[^\\/]+/, '');

  var isAsset = PRECACHE_URLS.some(function(p) { return path.endsWith(p) || path === p; });
  if (isAsset) {
    event.respondWith(
      caches.match(event.request).then(function(cached) {
        return cached || fetch(event.request).then(function(response) {
          return caches.open(CACHE_NAME).then(function(cache) {
            cache.put(event.request, response.clone());
            return response;
          });
        });
      })
    );
    return;
  }

  var isData = DATA_URLS.some(function(p) { return path.endsWith(p) || path === p; });
  if (isData) {
    event.respondWith(
      caches.match(event.request).then(function(cached) {
        var fetchPromise = fetch(event.request).then(function(response) {
          return caches.open(CACHE_NAME).then(function(cache) {
            cache.put(event.request, response.clone());
            return response;
          });
        });
        return cached || fetchPromise;
      })
    );
    return;
  }

  event.respondWith(fetch(event.request));
});

self.addEventListener('message', function(event) {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
`;

  fs.writeFileSync(SW_PATH, swCode, 'utf-8');
  console.log(`  Written: ${SW_PATH} (${(swCode.length / 1024).toFixed(1)} KB)`);
}

generateSW(INVERTER_DB);

// --- 5. Update PROJECT_MAP.md ---
if (fs.existsSync(PROJECT_MAP_PATH)) {
  let projectMap = fs.readFileSync(PROJECT_MAP_PATH, 'utf-8');

  const catalogDoc = `

---

## [INVERTER_CATALOG] — Unified Manufacturer Datasource
> Auto-generated from \`inverters-catalog.json\` on ${new Date().toISOString().split('T')[0]}

### Summary
| Metric | Value |
|--------|-------|
| Manufacturers | ${catalog.summary.totalManufacturers} |
| Series | ${catalog.summary.totalSeries} |
| **Total Models** | **${catalog.summary.totalModels}** |
| Type Distribution | LV: ${catalog.summary.typeDistribution.LV}, HV: ${catalog.summary.typeDistribution.HV} |
| Phase Distribution | 1φ: ${catalog.summary.phaseDistribution['1-phase']}, 3φ: ${catalog.summary.phaseDistribution['3-phase']} |

### Manufacturers & Models
`;

  let catalogTable = '| Brand | Series | Models | Type | Phase | Battery | MPPT Range | Max Charge A | Efficiency |\n';
  catalogTable += '|-------|--------|--------|------|-------|---------|------------|--------------|------------|\n';

  for (const mfr of catalog.manufacturers) {
    for (const series of mfr.series) {
      catalogTable += `| ${mfr.name} | ${series.name} | ${series.models.length} | ${series.type} | ${series.phase} | ${series.batteryVoltageRange[0]}-${series.batteryVoltageRange[1]}V | ${series.mpptVoltageRange[0]}-${series.mpptVoltageRange[1]}V | ${series.models.map(m => m.maxChargeCurrentA).join('/')}A | ${(series.maxEfficiency * 100).toFixed(1)}% |\n`;
    }
  }

  const sourceUrls = `
### Source URLs (Official Manufacturer Datasheets)
| Manufacturer | URL |
|--------------|-----|
| Solis | ${catalog.summary.sourceUrls.solis} |
| Voltronic (Axpert) | ${catalog.summary.sourceUrls.voltronic} |
| Megarevo (G2S) | ${catalog.summary.sourceUrls.megarevo} |
| Deye | ${catalog.summary.sourceUrls.deye} |
`;

  const ingestionNote = `
### Build Pipeline
\`\`\`bash
node build.mjs
\`\`\`
- Generates \`assets/inverter-db.js\` (ESM) from \`inverters-catalog.json\`
- Generates PWA icons from \`icons/icon.svg\` via sharp
- Generates \`sw.js\` with up-to-date precache manifest
`;

  const newProjectMap = projectMap + catalogDoc + catalogTable + sourceUrls + ingestionNote;
  fs.writeFileSync(PROJECT_MAP_PATH, newProjectMap);
  console.log('  Updated PROJECT_MAP.md');
}

// --- 6. Summary ---
console.log('\n BUILD COMPLETE');
console.log(`   Models: ${INVERTER_DB.length}`);
console.log(`   Files: assets/inverter-db.js, sw.js, icons/*, PROJECT_MAP.md`);
console.log(`   Source: inverters-catalog.json (${catalog.version})`);
